version: "3.9"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: safarticket
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build: ./SafarTicket
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./SafarTicket:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  db_data:

