version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: safarticket
      MYSQL_ROOT_PASSWORD: Aliprs2005
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build: ./SafarTicket
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./SafarTicket:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - EMAIL_USER=safarticket00@gmail.com
      - EMAIL_PASS=jgtivimugkolefyi
      - DJANGO_SETTINGS_MODULE=SafarTicket.settings

volumes:
  db_data:
